version: "3"
services:
    client:
        image: nowgnas/osakak:devclient
        container_name: devclient
        ports:
            - 3001:3001
        environment:
            VITE_APP_BASEURL: localhost:8081/api
        networks:
            - osakakdev
    backend:
        image: nowgnas/osakak:devserver
        container_name: devserver
        ports:
            - 8081:8081
        environment:
            USE_PROFILE: dev
            USERNAME: devnowgnas
            PASSWORD: dltkddnjs
            PROJECT: osakak
            NAME: osakakdev
        networks:
            - osakakdev
networks:
    osakakdev:
        external:
            name: osakakdev
