version: "3"

services:
  web-server:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
  blue:
    image: ${YOUR_APPLICATION_IMAGE}
    container_name: ${YOUR_APPLICATION_CONTAINER_NAME}
    restart: always
    expose:
      - "8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
  green:
    image: ${YOUR_APPLICATION_IMAGE}
    container_name: ${YOUR_APPLICATION_CONTAINER_NAME}
    restart: always
    expose:
      - "8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
