version: "3"
services:
    client:
        image: nowgnas/osakak:client
        container_name: client
        ports:
            - 3000:3000
        environment:
            VITE_APP_BASEURL: https://j8a504.p.ssafy.io/api
        networks:
            - osakak
    backend:
        image: nowgnas/osakak:server
        container_name: server
        ports:
            - 8083:8083
        environment:
            USE_PROFILE: prod
            USERNAME: osakak
            PASSWORD: wntkdskrdnjs
            HOST: localhost
            PORT: 27017
            DATABASE: osakak
        networks:
            - osakak
networks:
    osakak:
        external:
            name: osakak
