version: "3"
services:
    client:
        image: nowgnas/osakak:stageclient
        container_name: stageclient
        ports:
            - 3002:3002
        environment:
            VITE_APP_BASEURL: http://34.125.110.36:8082/api
        networks:
            - osakakstage
    backend:
        image: nowgnas/osakak:stageserver
        container_name: stageserver
        ports:
            - 8082:8082
        environment:
            USE_PROFILE: staging
            USERNAME: devnowgnas
            PASSWORD: dltkddnjs
            PROJECT: osakak
            NAME: osakakstaging
        networks:
            - osakakstage
networks:
    osakakstage:
        external:
            name: osakakstage
